import Link from "next/link";
import { savePlayer, togglePlayer } from "@/lib/actions";
import { getPlayers } from "@/lib/data";
import { FOOTBALL_POSITIONS } from "@/types/domain";
import ConfirmationForm from "@/components/confirmation-form";

export const dynamic = "force-dynamic";

export default async function PlayersPage({ searchParams }: { searchParams: Promise<{ edit?: string }> }) {
  const players = await getPlayers(); const { edit } = await searchParams; const selected = players.find((player) => player.id === edit);
  return <section className="space-y-5"><header><h1 className="text-2xl font-bold">Jugadores</h1><p className="text-sm text-slate-600">Administrá el plantel activo.</p></header>
    <ConfirmationForm key={selected?.id ?? "new-player"} action={savePlayer} kind="player" confirm={Boolean(selected)} className="card grid gap-3 md:grid-cols-4"><input type="hidden" name="id" value={selected?.id ?? ""}/>{selected && <div className="md:col-span-4 flex items-center justify-between"><p className="text-sm font-bold text-emerald-800">Editando a {selected.name}</p><Link className="text-sm font-bold text-emerald-800" href="/players">Cancelar</Link></div>}<label className="grid gap-1 text-sm font-medium">Nombre<input name="name" defaultValue={selected?.name ?? ""} required /></label><label className="grid gap-1 text-sm font-medium">Posición<select name="position" defaultValue={selected?.position ?? ""} required><option value="" disabled>Elegir</option>{FOOTBALL_POSITIONS.map((position) => <option key={position} value={position}>{position}</option>)}</select></label><label className="grid gap-1 text-sm font-medium">Estado físico<select name="physicalStatus" defaultValue={selected?.physical_status ?? "available"}><option value="available">Disponible</option><option value="minor_issue">Molestia / esguince leve</option><option value="injured">Lesionado</option></select></label><button className="button self-end" type="submit">{selected ? "Guardar cambios" : "Agregar jugador"}</button></ConfirmationForm>
    <div className="grid gap-3 sm:grid-cols-2">{players.map((player) => <article className="card flex items-center justify-between gap-3" key={player.id}><div><h2 className={player.physical_status === "injured" ? "font-bold text-red-700" : player.physical_status === "minor_issue" ? "font-bold text-amber-700" : "font-bold"}>{player.name}</h2><p className="text-sm text-slate-600">{player.position} · {player.active ? "Activo" : "Inactivo"} · {player.physical_status === "injured" ? "Lesionado" : player.physical_status === "minor_issue" ? "Molestia / esguince leve" : "Disponible"}</p></div><div className="flex gap-2"><Link className="button button-secondary" href={`/players?edit=${player.id}`}>Editar</Link><form action={togglePlayer}><input type="hidden" name="id" value={player.id}/><input type="hidden" name="active" value={String(player.active)}/><button className="button button-secondary" type="submit">{player.active ? "Desactivar" : "Activar"}</button></form></div></article>)}</div>
  </section>;
}
